### ISSUE TITLE
Potentially merge `flush_state` into `predict`

### ISSUE THREAD

**Issue by HyperCodec** [inflectrix/neat#32]
Because it's being constantly run after predictions anyway, it's probably wise to just merge the two and prevent the whole host of issues associated with it. Still not sure whether it's worth doing a refactor like this so late in development though.

**Comment by inflectrix** [comment]
One advantage to having flush_state be separate is that it's possible for someone to display the neuron states for a prediction in a little graph. I guess I'll keep it the current way until further notice (and maybe make a `plotters` widget at some point)
